javascript:(function(){
	trgr();
	function trgr(){
		d = window.open().document;
		d.writeln('<!DOCTYPE html>');
		d.writeln('<html lang="ja">');
		d.writeln('<head>');
		d.writeln('<meta charset="utf-8">');
		d.writeln('<title>Make-Bk</title>');
		d.writeln('<style type="text/css">');
		d.writeln('* {font-family:"メイリオ",Meiryo,sans-serif;}');
		d.writeln('input,textarea,label{font-size: 90%;}');
		d.writeln('button#bkm_create_btn {font-size:110%;}');
		d.writeln('dd {margin-left: 0;}');
		d.writeln('#bkm {border-collapse: collapse;width: 600px;}');
		d.writeln('#bkm th {background: #eee;border:3px solid #fff;padding: 5px;}');
		d.writeln('#bkm td {background: #FFFFE0;border:3px solid #fff;padding: 5px;}');
		d.writeln('#bkm_comments {width: 430px;}');
		d.writeln('.bkm-input {width: 370px;}');
		d.writeln('#bkm td.btnarea {text-align: center;background: #eee;}');
		d.writeln('#bkm td.codeare {background: #eee;}');
		d.writeln('#bkm_code {width: 600px; height: 10em;}');
		d.writeln('</style>');
		d.writeln('</head>');
		d.writeln('<body>');
		d.writeln('<script type="text/javascript">');
		d.writeln('function bkm_create(){');
		d.writeln('this.d = document;');
		d.writeln('this.bkm_head = "javascript:(function(){";');
		d.writeln('this.bkm_bottom = "})();";');
		d.writeln('this.bkm_body = "";');
		d.writeln('this.cat_hash = {');
		d.writeln('"bkm-browse-url": "browse-url",');
		d.writeln('};');
		d.writeln('}');
		d.writeln('bkm_create.prototype = {');
		d.writeln('exec: function() {');
		d.writeln('switch(this.get_selected_rdo()) {');
		d.writeln('case "bkm-browse-url":');
		d.writeln('this.browse_url();');
		d.writeln('break;');
		d.writeln('default:');
		d.writeln('break;');
		d.writeln('}');
		d.writeln('},');
		d.writeln('browse_url: function() {');
		d.writeln('var burl = this.d.getElementById("bkm-browse-url").value;');
		d.writeln('if(burl==="") {');
		d.writeln('alert("URLが入力されていません！");');
		d.writeln('return;');
		d.writeln('}');
		d.writeln('this.bkm_body += \'location.href="\' + burl + \'";\';');
		d.writeln('this.d.getElementById("bkm_code").value = this.bkm_head + this.bkm_body + this.bkm_bottom;');
		d.writeln('},');
		d.writeln('clear_this_text: function(obj) {');
		d.writeln('this.d.getElementById(obj).value = "";');
		d.writeln('},');
		d.writeln('br_escape: function(str) {');
		d.writeln('var ret = str.replace(/(\\\\r\\\\n|\\\\n)/mg, "\\\\n");');
		d.writeln('return ret;');
		d.writeln('},');
		d.writeln('search_cat: function(key) {');
		d.writeln('var bkey = this.cat_hash[key];');
		d.writeln('if(typeof bkey === "undefined" || bkey === null || bkey === "") return null;');
		d.writeln('return bkey;');
		d.writeln('},');
		d.writeln('get_selected_rdo: function() {');
		d.writeln('var ret = "";');
		d.writeln('var rds = this.d.getElementsByName("bkm-category");');
		d.writeln('for(var i=0; i<rds.length; i++) {');
		d.writeln('var rd = rds.item(i);');
		d.writeln('if(rd.checked === true) {');
		d.writeln('ret = rd.value;');
		d.writeln('break;');
		d.writeln('}');
		d.writeln('}');
		d.writeln('return ret;');
		d.writeln('}');
		d.writeln('};   ');
		d.writeln('var util = new bkm_create();  ');
		d.writeln('</script>');
		d.writeln('<h1>ブックマークレット生成</h1>');
		d.writeln('<table id="bkm">');
		d.writeln('<tr>');
		d.writeln('<th>');
		d.writeln('<label>');
		d.writeln('<input type="radio" name="bkm-category" value="bkm-browse-url">');
		d.writeln('指定URLへ移動');
		d.writeln('</label>');
		d.writeln('</th>');
		d.writeln('<td>');
		d.writeln('<input type="text" id="bkm-browse-url" class="bkm-input">');
		d.writeln('<button onclick="util.clear_this_text(\'bkm-browse-url\')">Clear</button>');
		d.writeln('</td>');
		d.writeln('</tr>');
		d.writeln('<tr>');
		d.writeln('<td colspan="2" class="btnarea">');
		d.writeln('<button id="bkm_create_btn" onclick="util.exec()">Create</button>');
		d.writeln('</td>');
		d.writeln('</tr>');
		d.writeln('<tr>');
		d.writeln('<td colspan="2" class="codearea"><textarea id="bkm_code"></textarea><br>');
		d.writeln('<button onclick="util.clear_this_text(\'bkm_code\')">Clear</button>');
		d.writeln('</td>');
		d.writeln('</tr>');
		d.writeln('</table>');
		d.writeln('</body>');
		d.writeln('</html>');
	}
})();